#+TITLE: .emacs.d

A personal Emacs configuration.

* Installation
** Clone the repository
#+begin_src sh
git clone https://github.com/yilin-zhang/.emacs.d.git ~/.emacs.d
cd ~/.emacs.d
git submodule update --init
#+end_src
** Install dependencies (macOS)
*** Global
#+begin_src sh
brew tap homebrew/cask-fonts
brew install coreutils font-sarasa-gothic font-noto-serif-cjk-sc
#+end_src
*** Package
**** color-rg
#+begin_src sh
brew install ripgrep
#+end_src
**** jinx
1. Install =enchant= and =pkgconf=
   #+begin_src sh
   brew install enchant pkgconf
   #+end_src

2. Override the configuration to use =AppleSpell= by default.
   Create or modify =~/.config/enchant/enchant.ordering=:
   #+begin_src
   *:AppleSpell
   en_US:AppleSpell
   #+end_src
**** nerd-icons
Install nerd fonts in Emacs: =M-x nerd-icons-install-fonts=
** LSP
| Language | Server                       |
|----------+------------------------------|
| Python   | `pyright`                    |
| JS/TS    | `typescript-langauge-server` |
| JSON     | `vscode-json-languageserver  |
| Vue      | `vue-language-server`        |
| Lua      | `lua-language-server`        |

* Customization
Create file =~/.emacs.d/custom/custom-post.el=. The configuration in the file will
be loaded last.

** Org
The most important configuration is to set =org-agenda-files=, so that Emacs knows
where you agenda files are.
#+begin_src elisp
(use-package org
  :ensure nil
  :config
  (add-to-list 'org-agenda-files "~/info.org")
  (add-to-list 'org-agenda-files "~/inbox.org")
  ;; org-ref
  (setq reftex-default-bibliography '("~/references.bib"))
  ;; see org-ref for use of these variables
  (setq org-ref-bibliography-notes "~/bib-notes.org"
        org-ref-default-bibliography '("~/references.bib")
        org-ref-pdf-directory "~/bibtex-pdfs/")
  )
#+end_src

** Elfeed (RSS)
Set the RSS feeds by setting =elfeed-feeds=. Example:
#+begin_src elisp
(setq elfeed-feeds '("https://protesilaos.com/books.xml"))
#+end_src

** Denote
Set the denote bucket by setting =denote-directory=. Example:
#+begin_src elisp
(setq denote-directory "~/Documents/notebooks/denote")
#+end_src

** Meow
Define some leader keys. Example:
#+begin_src elisp
(meow-leader-define-key
 '("t" . yilin/open-in-terminal)
 '("e" . yilin/open-in-finder))
#+end_src

